#!/bin/bash
#
#
# POST MODERN UNIX TOOLS
# pcd
#
# this program allows you to save directory aliases and easily
# change directories via the aliases. it is similar to pushd and popd
# in some ways.
#
# Copyright(c) 2018 by Christopher Abad
# aempirei@gmail.com
#
# this code is licensed under the "don't be a retarded asshole" license.
# if i don't like how you use this software i can tell you to fuck off
# and you can't use it, otherwise you can use it.
#
#

PCDRC="$HOME/.pcdrc"

touch "$PCDRC"

function s () {
	if [ -z "$1" ]; then
		echo an alias must be chosen
	elif [[ "$1" =~ ^- ]]; then
		echo "directory aliases cannot begin with dash (\"-\")"
	else
		dir=`pwd`
		echo saving directory alias "$1 => $dir"
		echo "$1" "$dir" >> "$PCDRC"
	fi
}

function d () {

	local -A pcd

	while read name dir; do
		pcd[$name]="$dir"
	done < "$PCDRC"

	if [ -z "$1" ]; then
		for name in "${!pcd[@]}"; do
			printf "%8s: %s\n" "$name" "${pcd[$name]}"
		done
	elif [ -n "${pcd[$1]}" ]; then
		cd "${pcd[$1]}"
	else
		echo "unknown directory alias '$1'" 1>&2
	fi
}
