#!/bin/bash
#
#
# POST MODERN UNIX TOOLS
# pcd
#
# this program allows you to save directory aliases and easily
# change directories via the aliases. it is similar to pushd and popd
# in some ways.
#
# Copyright(c) 2018 by Christopher Abad
# aempirei@gmail.com
#
# this code is licensed under the "don't be a retarded asshole" license.
# if i don't like how you use this software i can tell you to fuck off
# and you can't use it, otherwise you can use it.
#
#

PCDRC="$HOME/.pcdrc"

touch "$PCDRC"

declare -A PCDMAP

function s () {
	if [ -z "$1" ]; then
		echo "${FUNCNAME[0]} expects a non-empty directory alias argument" 1>&2
	elif [[ "$1" =~ ^- ]]; then
		echo "directory aliases cannot begin with dash (\"-\")"
	else
		dir=`pwd`
		echo saving directory alias "$1 => $dir"
		PCDMAP[$1]="$dir"
		declare -p PCDMAP > "$PCDRC"
	fi
}

function E () {
	if [ -n "$1" ]; then
		if [ -v "PCDMAP[$1]" ]; then
			unset PCDMAP[$1]
			declare -p PCDMAP > "$PCDRC"
		else
			echo "unknown directory alias '$1'" 1>&2
		fi
	else
			echo "${FUNCNAME[0]} expects a non-empty directory alias argument" 1>&2
	fi
}

function d () {
	if [ -z "$1" ]; then
		for name in "${!PCDMAP[@]}"; do
			printf "%8s: %s\n" "$name" "${PCDMAP[$name]}"
		done
	elif [ -v "PCDMAP[$1]" ]; then
		cd "${PCDMAP[$1]}"
	else
		echo "unknown directory alias '$1'" 1>&2
	fi
}

. "$PCDRC"
