#!/bin/bash
#
#
# POST MODERN UNIX TOOLS
# pf
#
# this program allows you to save directory aliases and easily
# change directories via the aliases. it is similar to pushd and popd
# if you would like, add the aliases 'd' and 's' via either runnning pcd -a
# from your bashrc or adding them to your aliasrc file by running pcd -A
# to print the alias commands to screen and copying them into your aliasrc.
#
# Copyright(c) 2010 by Christopher Abad
# aempirei@gmail.com
#
# this code is licensed under the "don't be a retarded asshole" license.
# if i don't like how you use this software i can tell you to fuck off
# and you can't use it, otherwise you can use it.
#
#

pcdrc="$HOME/.pcdrc"

if [ ! -f "$pcdrc" ]; then
	touch "$pcdrc"
fi

# dont forget, never use the 'exit' command because this script
# is invoked with '.' prefix to execute in the current interpreter.

if [ "$1" == "" ]; then

	# no arguments, list the directory aliases

	echo
	echo '[ directory aliases ]'
	echo
	cat $pcdrc | tr " " "\t" | while read a; do echo -e "\t$a"; done
	echo

elif [ "$1" == "-h" ]; then

	# -h for help

	cat <<__EOF__

usage: $0 [options] [alias]

save and recall directory aliases. no arguments will list all saved aliases
just an alias and no options will recall the specified directory alias and change
the working directory.

	-s alias	save the current working directory with the specified directory alias
	-a			set the 'd' and 's' bash aliases
	-A			print the bash alias commands
	-V			show version
	-h			show this help

some usage examples are the following

	pcd -s root
	pcd root
	pcd -A >> ~/.bashrc

PMUT/pcd version `pextract -V | pextract 'version (\S+)'`
report bugs to <aempirei@gmail.com>

__EOF__

elif [ "$1" == "-V" ]; then

	echo PMUT/pcd version `pextract -V | pextract 'version (\S+)'`

elif [ "$1" == "-s" ]; then

	# -s alias | save the current working directory alias

	if [ "$2" == "" ]; then
		echo an alias must be chosen
	elif [[ "$2" =~ ^- ]]; then
		echo "directory aliases cannot begin with dash (\"-\")"
	else
		dir=`pwd`
		echo saving directory alias "$2 => $dir"
		echo "$2" "$dir" >> $pcdrc
	fi

elif [ "$1" == "-a" ]; then

	# -a | set the bash aliases for 'd' and 's'

	alias d='. pcd'
	alias s='. pcd -s'

elif [ "$1" == "-A" ]; then

	# -A | print the bash alias commands to be added to the aliasrc or bashrc

	echo "alias d='. pcd'"
	echo "alias s='. pcd -s'"
else

	# perform the directory alias recall

	while read alias dir; do
		if [ "$alias" == "$1" ]; then
			echo "changing directory to $dir"
			cd "$dir"
			break
		fi
	done < $pcdrc
fi



