#!/bin/bash

if [ "$1" == "" ] || [ "$1" == "-h" ]; then
	cat <<__EOF__

usage: $0 [options] from_pcre to_pcre

from should be a pcre match pattern and the to should be the replace pattern.

	-t	test only. only generate and print the mv commands
		that would perform the rename
	-V	show version
	-h	show this help

some usage examples are the following

	prename '\.pl\$' '.php'
	prename -t '^(.+)\.(.+)\$' '\2_\1.txt'

PMUT/prename version `pextract -V | pextract 'version (\S+)'`
report bugs to <aempirei@gmail.com>

__EOF__

	exit

elif [ "$1" == "-V" ]; then

    echo PMUT/prename version `pextract -V | pextract 'version (\S+)'`
	exit
fi

# check for test-only mode

test=false

if [ "$1" == "-t" ]; then
	test=true
	shift
fi

$test && echo '# test-mode'

from="$1"
to="$2"

ls -d * | pcregrep "$from" | while read from_file; do
	to_file=`echo "$from_file" | perl -pe "s/$from/$to/"`
	if $test; then
		echo mv -v "$from_file" "$to_file"
	else
		mv -v "$from_file" "$to_file"
	fi
done


